name: Anders
main: Anders\Main
version: 1.0.0
api: [3.0.0, 4.0.0]
load: POSTWORLD
author: Anders
commands:
 Anders:
  description: "AndersPluginCommand"
  usage: "/Anders"
  permission: Anders.command
permissions:
 Anders.command:
  default: true
