name: PlayerJoinSettings
main: Anders\PlayerJoinSettings\Main
version: 3.0.0
api: 3.0.0
load: POSTWORLD
authors: 
- Anders
- wode490390
commands:
 joinset:
  description: "PlayerJoinSettingsCommand"
  usage: "/joinset"
  permission: PlayerJoinSettings.command
permissions:
 PlayerJoinSettings.command:
  default: op
