name: Anders
main: Anders\Main
version: 1.0.0
api: [4.0.0]
load: POSTWORLD
author: Anders
commands:
 Anders:
  description: "AndersPlugin"
  usage: "/Anders"
  permission: MyPlugin.command.yoo
permissions:
 Anders.*:
  description: "OP"
  default: op
 Anders.command.Anders:
  description: "Player"
  default: true
