name: PlayerJoinSettings
main: Anders\PlayerJoinSettings\Main
version: 1.0.0
api: [3.0.0, 4.0.0]
load: POSTWORLD
author: Anders
commands:
 reloadconfig:
  description: "reload PlayerJoinSettings config"
  usage: "/reloadconfig"
  permission: PlayerJoinSettings.command.reloadconfig
permissions:
 PlayerJoinSettings.command.reloadconfig:
  default: op
