name: PlayerJoinSettings
main: Anders\PlayerJoinSettings\Main
version: 1.1.1
api: 3.0.0
load: POSTWORLD
author: Anders
commands:
 joinset:
  description: "PlayerJoinSettingsCommand"
  usage: "/joinset"
  permission: PlayerJoinSettings.command
permissions:
 PlayerJoinSettings.command:
  default: op
