---
# Currently supported tags:
# {name}          - The name of the player.
# {line}          - Switch to the next line.
# {online}        - The number of online players currently on the server
# {max_online}    - The maximum number of players the server can accommodate
# You can also use & replace with color symbols.

# The headline on the screen when joining (Title).
Title: "&l&6Welcome!"

# The text above the item bar when you join (SubTitle).
SubTitle: "&bThis is a great server"

# Private chat message sent to the player when joining (Message).
Message: "&aHello {name}. {line}&bwelcome to this server. {line}&eI wish you a happy time!"

# Server broadcast message when the player joins (PlayerJoinMessage).
PlayerJoinMessage: "&l&7(&9 + &7) &r&a{name} &ejoined the server.&7[&a{online}&7/&6{max_online}&7]"

# Server broadcast message when the player Quits (PlayerQuitMessage).
PlayerQuitMessage: "&l&7(&c - &7) &r&a{name} &eQuit the server.&7[&a{online}&7/&6{max_online}&7]"
...
