---
# Currently supported tags:
# {name} - The name of the player.
# {line} - Switch to the next line.
# You can also use & replace with color symbols.

# The headline on the screen when joining (Title).
Title: "&l&6Welcome!"

# The text above the item bar when you join (SubTitle).
SubTitle: "&bThis is a great server"

# Private chat message sent to the player when joining (Message).
Message: "&aHello {name}. {line}&bwelcome to this server. {line}&eI wish you a happy time!"

# Server broadcast message when the player joins (PlayerJoinMessage).
PlayerJoinMessage: "&l&7(&9+&7) &r&a{name} &ejoined the server."

# Server broadcast message when the player Quits (PlayerQuitMessage).
PlayerQuitMessage: "&l&7(&c-&7) &r&a{name} &eQuit the server."
...
